language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before-install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - composer check
  - composer test

env:
  - CODECOV_TOKEN="f6aa029b-aa99-4481-b415-3d0b126b7cd8"


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: contato@gilbertoalbino.com